# Generated by Django 2.1.7 on 2019-05-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=1000)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Category', models.CharField(max_length=50)),
            ],
        ),
    ]
